---
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: mixed-line-ending
        -   id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.13.1
      hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
      -   id: pydocstyle
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1
      hooks:
      -   id: mypy
    - repo: local
      hooks:
          # Note: pylint to be run locally:
          # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args:
              [
                --rcfile=.pylintrc
              ]
